language: node_js

stages:
  - lint
  - build
  - test
  - release

notifications:
  email: false

cache:
  directories:
    - dist

jobs:
  include:
    - stage: lint
      node_js: node
      script:
        - npm run lint
        - prettier --check './*.json' './*.yml'

    - &build
      stage: build
      node_js: lts/*
      script:
        - npm run build

    - <<: *build
      node_js: node

    - &test-unit
      stage: test
      node_js: lts/*
      name: 'Unit Tests  Latest LTS'
      script:
        - npm run test:unit -- --coverage
        - npm run coverage

    - &test-integration
      stage: test
      node_js: lts/*
      name: 'Integration Tests Latest LTS'
      env:
        - GITLAB_URL=https://localhost:8080
      before_script:
        - cd test/docker/

        # Spin up container
        - docker-compose -f docker-compose.test.yml up -d

        # Verify Gitlab instance is up and running
        - bash test_readiness.sh

        # Get the personal token
        - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')

        # Display configuration
        - echo $GITLAB_URL
        - echo $PERSONAL_ACCESS_TOKEN
      script:
        - npm run test:integration -- --coverage
        - npm run coverage

    - <<: *test-unit
      name: 'Unit Tests Latest'
      node_js: node
      script:
        - npm run test:unit

    - <<: *test-integration
      name: 'Integration Tests Latest'
      node_js: node
      script:
        - npm run test:integration

    - stage: release
      node_js: node
      script:
        - npm run release
